version: "3"
services:
  backend:
    container_name: "sushi-bai-kiyoshi"
    image: python:3
    build: .
    command: python app.py
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/srv/backend:rw
    working_dir: /srv/backend

volumes:
  bsc-pgdata: {}
